# Generated by Django 5.2.8 on 2025-11-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
